const fs = require('fs');

// 更完整的翻译词典
const dict = {
  // ===== 常用动词 =====
  'Oversee': '负责监管',
  'Manage': '管理',
  'Managing': '负责',
  'Lead': '负责',
  'Leading': '负责',
  'Support': '支持',
  'Coordinate': '协调',
  'Collaborate': '协作',
  'Develop': '开发/制定',
  'Design': '设计',
  'Implement': '实施',
  'Maintain': '维护',
  'Analyze': '分析',
  'Monitor': '监控',
  'Review': '审核',
  'Create': '创建',
  'Build': '构建',
  'Ensure': '确保',
  'Provide': '提供',
  'Contribute': '贡献',
  'Drive': '推动',
  'Deliver': '交付',
  'Execute': '执行',
  'Optimize': '优化',
  'Improve': '改进',
  'Enhance': '增强',
  
  // ===== 形容词/副词 =====
  'Strong': '强',
  'Excellent': '优秀',
  'Outstanding': '出色',
  'Proficient': '熟练',
  'Experienced': '有经验的',
  'Skilled': '熟练的',
  'Advanced': '高级的',
  'Proven': '经过验证的',
  'Comprehensive': '全面的',
  'Deep': '深入的',
  'Stronger': '更强的',
  
  // ===== 名词 - 学位 =====
  "Bachelor's degree": '本科学历',
  "Bachelor's": '本科',
  'Bachelor': '本科',
  "Master's degree": '硕士学历',
  "Master's": '硕士',
  'Master': '硕士',
  'PhD': '博士',
  'Degree': '学位',
  
  // ===== 名词 - 职位级别 =====
  'Senior': '高级',
  'Junior': '初级',
  'Lead': '负责人',
  'Manager': '经理',
  'Director': '总监',
  'Head': '负责人',
  'VP': '副总裁',
  'Executive': '高管',
  'Intern': '实习',
  'Associate': '专员',
  'Specialist': '专员',
  'Coordinator': '协调员',
  'Officer': '专员',
  'Chief': '首席',
  'Principal': '资深',
  
  // ===== 名词 - 部门 =====
  'Product': '产品',
  'Engineering': '工程',
  'Technology': '技术',
  'Design': '设计',
  'Marketing': '市场',
  'Sales': '销售',
  'Operations': '运营',
  'Finance': '财务',
  'Legal': '法务',
  'HR': '人力资源',
  'Human Resources': '人力资源',
  'Compliance': '合规',
  'Customer Service': '客户服务',
  'Business': '业务',
  
  // ===== 名词 - 专业技能/工具 =====
  'Java': 'Java',
  'Python': 'Python',
  'Go': 'Go',
  'Golang': 'Go',
  'JavaScript': 'JavaScript',
  'TypeScript': 'TypeScript',
  'React': 'React',
  'Vue.js': 'Vue',
  'Vue': 'Vue',
  'Node.js': 'Node.js',
  'Node': 'Node.js',
  'SQL': 'SQL',
  'API': 'API',
  'AI': '人工智能',
  'ML': '机器学习',
  'Machine Learning': '机器学习',
  'PM': '产品经理',
  'Big Data': '大数据',
  'Cloud': '云',
  'AWS': 'AWS',
  'GCP': 'GCP',
  'Azure': 'Azure',
  'Docker': 'Docker',
  'Kubernetes': 'Kubernetes',
  'K8s': 'Kubernetes',
  
  // ===== 名词 - 行业 =====
  'Crypto': '加密货币',
  'Cryptocurrency': '加密货币',
  'Blockchain': '区块链',
  'Fintech': '金融科技',
  'Exchange': '交易所',
  'Trading': '交易',
  'DeFi': '去中心化金融',
  'Web3': 'Web3',
  'CEX': '中心化交易所',
  'DEX': '去中心化交易所',
  
  // ===== 名词 - 能力/技能 =====
  'Skills': '技能',
  'Skill': '技能',
  'Expertise': '专业知识',
  'Knowledge': '知识',
  'Experience': '经验',
  'Ability': '能力',
  'Capability': '能力',
  'Communication': '沟通能力',
  'Leadership': '领导力',
  'Problem-solving': '解决问题的能力',
  'Analytical': '分析能力',
  'Project Management': '项目管理',
  'Data Analysis': '数据分析',
  'Teamwork': '团队合作',
  
  // ===== 常用短语 =====
  'Work experience': '工作经验',
  'Years of experience': '年工作经验',
  'Proven track record': '良好业绩记录',
  'Track record': '业绩记录',
  'Strong communication skills': '沟通能力强',
  'Excellent communication': '优秀沟通能力',
  'Problem-solving skills': '解决问题的能力',
  'Analytical skills': '分析能力',
  'Leadership skills': '领导力',
  'Teamwork skills': '团队合作能力',
  'Full-time': '全职',
  'Part-time': '兼职',
  'Remote work': '远程工作',
  'Remote': '远程',
  'Competitive salary': '有竞争力的薪资',
  'Health insurance': '医疗保险',
  'Annual leave': '年假',
  'Flexible hours': '弹性工作时间',
  'Benefits': '福利',
  'Bonus': '奖金',
  'Stock options': '股票期权',
  
  'Nice to have': '优先考虑',
  'Must have': '必备',
  'Plus': '加分',
  'Preferred': '优先',
  'Required': '必需',
  
  'Fluent in English': '英语流利',
  'Fluent in Chinese': '中文流利',
  'Native English speaker': '英语母语',
  'Native Chinese speaker': '中文母语',
  'Written and spoken': '书面和口语',
  'Business level': '商务级别',
  
  'Cross-functional': '跨部门',
  'Stakeholder': '利益相关方',
  'Stakeholder management': '相关方管理',
  'Risk management': '风险管理',
  'Content creation': '内容创作',
  'Social media': '社交媒体',
  'Digital marketing': '数字营销',
  'Growth hacking': '增长黑客',
  'User experience': '用户体验',
  'User research': '用户研究',
  'Product management': '产品管理',
  'Business development': '业务拓展',
  'Key account': '关键客户',
  'Event planning': '活动策划',
  'Community management': '社区管理',
  'Customer service': '客户服务',
  'Technical support': '技术支持',
  'Quality assurance': '质量保证',
  
  'Strategy': '策略',
  'Strategic': '战略',
  'Process': '流程',
  'Platform': '平台',
  'System': '系统',
  'Tools': '工具',
  'Solutions': '解决方案',
  'Requirements': '需求',
  'Features': '功能',
  'Users': '用户',
  'Customers': '客户',
  'Partners': '合作伙伴',
  'Teams': '团队',
  'Stakeholders': '利益相关方',
  'Metrics': '指标',
  'KPIs': '关键绩效指标',
  'Performance': '绩效',
  'Revenue': '收入',
  'Growth': '增长',
  'Engagement': '参与度',
  'Conversion': '转化',
  'Retention': '留存',
  'Acquisition': '获客',
  
  'Daily': '每日',
  'Weekly': '每周',
  'Monthly': '每月',
  'Quarterly': '每季度',
  'Annually': '每年',
  
  // ===== 常见英文单词 =====
  'years': '年',
  'year': '年',
  'months': '个月',
  'month': '个月',
  'team': '团队',
  'product': '产品',
  'user': '用户',
  'customer': '客户',
  'market': '市场',
  'business': '业务',
  'company': '公司',
  'role': '角色',
  'position': '职位',
  'job': '工作',
  'work': '工作',
  'project': '项目',
  'task': '任务',
  'goal': '目标',
  'result': '结果',
  'data': '数据',
  'information': '信息',
  'report': '报告',
  'analysis': '分析',
  'research': '研究',
  'plan': '计划',
  'strategy': '策略',
  'solution': '解决方案',
  'process': '流程',
  'system': '系统',
  'service': '服务',
  'support': '支持',
  'help': '帮助',
  'need': '需要',
  'require': '需要',
  'must': '必须',
  'should': '应该',
  'can': '可以',
  'will': '将',
  'would': '会',
  'could': '能',
  'may': '可能',
  'provide': '提供',
  'give': '给',
  'take': '取',
  'make': '做',
  'do': '做',
  'use': '使用',
  'utilize': '利用',
  'apply': '应用',
  'handle': '处理',
  'deal': '处理',
  'solve': '解决',
  'resolve': '解决',
  'fix': '修复',
  'improve': '改进',
  'enhance': '增强',
  'increase': '增加',
  'decrease': '减少',
  'reduce': '减少',
  'minimize': '最小化',
  'maximize': '最大化',
  'develop': '开发',
  'create': '创建',
  'build': '构建',
  'design': '设计',
  'plan': '计划',
  'organize': '组织',
  'manage': '管理',
  'lead': '领导',
  'guide': '指导',
  'train': '培训',
  'teach': '教',
  'learn': '学习',
  'understand': '理解',
  'know': '知道',
  'remember': '记得',
  'think': '思考',
  'consider': '考虑',
  'evaluate': '评估',
  'assess': '评估',
  'measure': '衡量',
  'test': '测试',
  'check': '检查',
  'verify': '验证',
  'confirm': '确认',
  'ensure': '确保',
  'guarantee': '保证',
  'find': '发现',
  'discover': '发现',
  'identify': '识别',
  'recognize': '认识',
  'see': '看到',
  'look': '看',
  'watch': '观看',
  'read': '阅读',
  'write': '写',
  'speak': '说',
  'talk': '谈',
  'say': '说',
  'tell': '告诉',
  'ask': '问',
  'answer': '回答',
  'reply': '回复',
  'discuss': '讨论',
  'explain': '解释',
  'describe': '描述',
  'summarize': '总结',
  'report': '报告',
  'present': '展示',
  'show': '显示',
  'display': '显示',
  'demonstrate': '演示',
  'illustrate': '说明',
  'compare': '比较',
  'contrast': '对比',
  'differ': '不同',
  'similar': '相似',
  'like': '像',
  'unlike': '不像',
  'relate': '相关',
  'connect': '连接',
  'link': '链接',
  'associate': '关联',
  'depend': '依赖',
  'affect': '影响',
  'impact': '影响',
  'influence': '影响',
  'relate to': '关于',
  'according to': '根据',
  'based on': '基于',
  'due to': '由于',
  'because of': '因为',
  'thanks to': '多亏',
  'regardless of': '不管',
  'despite': '尽管',
  'although': '虽然',
  'while': '虽然',
  'however': '然而',
  'but': '但是',
  'yet': '然而',
  'also': '也',
  'too': '也',
  'as well': '也',
  'in addition': '此外',
  'additionally': '另外',
  'furthermore': '而且',
  'moreover': '此外',
  'besides': '除此之外',
  'especially': '尤其',
  'particularly': '特别',
  'mainly': '主要',
  'primarily': '主要',
  'generally': '通常',
  'usually': '通常',
  'often': '经常',
  'sometimes': '有时',
  'occasionally': '偶尔',
  'rarely': '很少',
  'seldom': '很少',
  'never': '从不',
  'always': '总是',
  'constantly': '不断地',
  'continuously': '持续地',
  'regularly': '定期地',
  'frequently': '频繁地',
  'again': '再次',
  'once': '一次',
  'twice': '两次',
  'first': '首先',
  'second': '第二',
  'third': '第三',
  'then': '然后',
  'next': '接下来',
  'after': '之后',
  'before': '之前',
  'during': '期间',
  'through': '通过',
  'throughout': '整个',
  'within': '在之内',
  'outside': '之外',
  'beyond': '超出',
  'above': '以上',
  'below': '以下',
  'over': '超过',
  'under': '低于',
  'more than': '超过',
  'less than': '少于',
  'at least': '至少',
  'at most': '最多',
  'approximately': '大约',
  'about': '大约',
  'around': '大约',
  'nearly': '几乎',
  'almost': '差不多',
  'quite': '相当',
  'very': '非常',
  'extremely': '极其',
  'really': '真的',
  'truly': '真正地',
  'actually': '实际上',
  'in fact': '事实上',
  'as a matter of fact': '事实上',
  'of course': '当然',
  'certainly': '当然',
  'surely': '确实',
  'definitely': '肯定',
  'absolutely': '绝对',
  'totally': '完全',
  'completely': '完全',
  'entirely': '完全地',
  'wholly': '完全',
  'partially': '部分地',
  'partly': '部分地',
  'mainly': '主要',
  'mostly': '主要',
  'largely': '主要',
};

// 转换为正则替换
const entries = Object.entries(dict).sort((a, b) => b[0].length - a[0].length);

function translate(text) {
  if (!text) return text;
  
  let result = text;
  
  entries.forEach(([en, zh]) => {
    const regex = new RegExp(en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
    result = result.replace(regex, zh);
  });
  
  // 后处理
  result = result.replace(/(\d+)\s*years?\s*of\s*experience/gi, '$1年工作经验');
  result = result.replace(/(\d+)\s*\+\s*years?/gi, '$1+年');
  result = result.replace(/(\d+)\s*years?/gi, '$1年');
  result = result.replace(/(\d+)\s*months?/gi, '$1个月');
  result = result.replace(/(\d+)\s*days?/gi, '$1天');
  
  // 清理残留
  result = result.replace(/English and Mandarin/gi, '英语和普通话');
  result = result.replace(/English or Chinese/gi, '英语或中文');
  result = result.replace(/Chinese and English/gi, '中文和英文');
  result = result.replace(/both Chinese and English/gi, '中英文双语');
  result = result.replace(/and\/or/gi, '和/或');
  
  return result;
}

// 读取数据
const data = JSON.parse(fs.readFileSync('./src/data/jobs.json', 'utf8'));

console.log('开始翻译...');

let translated = 0;
data.forEach((job, index) => {
  let changed = false;
  
  if (job.jobDescription) {
    const before = job.jobDescription;
    job.jobDescription = translate(job.jobDescription);
    if (before !== job.jobDescription) changed = true;
  }
  
  if (job.requirements) {
    const before = job.requirements;
    job.requirements = translate(job.requirements);
    if (before !== job.requirements) changed = true;
  }
  
  if (job.aboutUs) {
    const before = job.aboutUs;
    job.aboutUs = translate(job.aboutUs);
    if (before !== job.aboutUs) changed = true;
  }
  
  if (changed) translated++;
  
  if ((index + 1) % 20 === 0) {
    console.log(`已完成 ${index + 1}/${data.length}`);
  }
});

fs.writeFileSync('./src/data/jobs.json', JSON.stringify(data, null, 2));
console.log(`翻译完成！共处理 ${translated} 个岗位`);
